version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
      # more setup needed for aws, node, elastic beanstalk
    steps:
      - node/install:
          node-version: "16.17.1"
      - checkout
      - run:
          name: Install packages
          # TODO: Install, build, deploy in both apps
          command: |
            npm install
      - run:
          name: build packages
          # TODO: Install, build, deploy in both apps
          command: |
            npm run build
  deploy:
    docker:
      - image: "cimg/base:stable"
      # more setup needed for aws, node, elastic beanstalk
    steps:
      - node/install:
          node-version: "16.17.1"
      - checkout
      - run:
          name: Add .env
          # TODO: Install, build, deploy in both apps
          command: |
            echo  PASS=$PASS PEPPER=$PEPPER > ./.env && cat .env
      - run:
          name: Deploy to heroku
          # TODO: Install, build, deploy in both apps
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
workflows:
  build and deploy:
    jobs:
      - build
      - hold:
          filters:
            branches:
              only:
                - master
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
